name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - Task-4---Spin-up-NestJS-Service

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install global dependencies
        run: npm install -g aws-cdk

      - name: Install backend dependencies
        run: cd src/backend/NestJS && npm ci

      - name: Build backend
        run: cd src/backend/NestJS && npm run build

      - name: Install frontend dependencies
        run: cd src/frontend && npm ci

      - name: Build frontend
        run: cd src/frontend && npm run build

      - name: Install CDK dependencies
        run: cd infra/cdk && npm ci

      - name: Build CDK
        run: cd infra/cdk && npm run build

      - name: Deploy CDK Stack
        run: cd infra/cdk && npx cdk deploy --require-approval never
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
